// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF9FsHfw9v-CRlNsdB-BsOzXS7hLvz0RQ',
    appId: '1:434290360981:web:9ac68bb5e6399924e1d19c',
    messagingSenderId: '434290360981',
    projectId: 'minesmart-c5373',
    authDomain: 'minesmart-c5373.firebaseapp.com',
    storageBucket: 'minesmart-c5373.firebasestorage.app',
    measurementId: 'G-ZEW3YCQLP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJRSv7oJIIwoTv-mtb1Ho6y9rVMf3_5w',
    appId: '1:434290360981:android:33ca6d4fd698aa75e1d19c',
    messagingSenderId: '434290360981',
    projectId: 'minesmart-c5373',
    storageBucket: 'minesmart-c5373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNqg1acod5ClA3dizCaLxmxL9zBGRYVV0',
    appId: '1:434290360981:ios:3c2a57365eecc1a7e1d19c',
    messagingSenderId: '434290360981',
    projectId: 'minesmart-c5373',
    storageBucket: 'minesmart-c5373.firebasestorage.app',
    iosBundleId: 'com.example.mineSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNqg1acod5ClA3dizCaLxmxL9zBGRYVV0',
    appId: '1:434290360981:ios:3c2a57365eecc1a7e1d19c',
    messagingSenderId: '434290360981',
    projectId: 'minesmart-c5373',
    storageBucket: 'minesmart-c5373.firebasestorage.app',
    iosBundleId: 'com.example.mineSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF9FsHfw9v-CRlNsdB-BsOzXS7hLvz0RQ',
    appId: '1:434290360981:web:74ab505bb957e07fe1d19c',
    messagingSenderId: '434290360981',
    projectId: 'minesmart-c5373',
    authDomain: 'minesmart-c5373.firebaseapp.com',
    storageBucket: 'minesmart-c5373.firebasestorage.app',
    measurementId: 'G-NQZ6XPQGKF',
  );
}
